/**
 * GET /api/pending-fixes - List all pending fixes from AI detection
 *
 * These are fixes generated by the real AI pipeline (not hardcoded),
 * waiting for approval before being applied via PR.
 */

import { NextResponse } from 'next/server';
import { pendingFixes } from '../events/route';

export async function GET() {
  const pending = pendingFixes.filter(f => !f.applied);
  const applied = pendingFixes.filter(f => f.applied);

  return NextResponse.json({
    success: true,
    pending: pending.map(f => ({
      id: f.id,
      generatedAt: f.generatedAt,
      fixType: f.fixType,
      actionType: f.mapping?.actionMapping?.suggestedAction?.actionType ||
                  f.mapping?.fixType ||
                  'unknown',
      patchCount: f.mapping?.generatedCode?.patches?.length ||
                  f.mapping?.patches?.length ||
                  0,
      explanation: f.mapping?.generatedCode?.explanation ||
                   f.mapping?.explanation ||
                   'No explanation',
      approveUrl: `/api/pending-fixes/${f.id}/approve`,
    })),
    appliedCount: applied.length,
    pendingCount: pending.length,
  });
}
